apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: prometheus-csi-monitor
  name: prometheus-csi-monitor
  namespace: default
spec:
  podMetricsEndpoints: [
    path: /metrics,
    port: "8787",
    interval: "15",
    scrapeTimeout: "300"
  ]
  selector:
    matchLabels:
      app: csi-baremetal
      app.kubernetes.io/name: csi-baremetal
  namespaceSelector:
    matchNames: [default]
